// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalRLiveSportsDashboard.Data;

namespace SignalRLiveSportsDashboard.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20211216184122_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SignalRLiveSportsDashboard.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Team1")
                        .HasColumnType("int");

                    b.Property<int?>("Team1Goals")
                        .HasColumnType("int");

                    b.Property<int?>("Team2")
                        .HasColumnType("int");

                    b.Property<int?>("Team2Goals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Team1");

                    b.HasIndex("Team2");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("SignalRLiveSportsDashboard.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Logo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SignalRLiveSportsDashboard.Models.Match", b =>
                {
                    b.HasOne("SignalRLiveSportsDashboard.Models.Team", "Team1Navigation")
                        .WithMany("MatchTeam1Navigations")
                        .HasForeignKey("Team1")
                        .HasConstraintName("FK_Matches_Team1_Teams_Id");

                    b.HasOne("SignalRLiveSportsDashboard.Models.Team", "Team2Navigation")
                        .WithMany("MatchTeam2Navigations")
                        .HasForeignKey("Team2")
                        .HasConstraintName("FK_Matches_Team2_Teams_Id");

                    b.Navigation("Team1Navigation");

                    b.Navigation("Team2Navigation");
                });

            modelBuilder.Entity("SignalRLiveSportsDashboard.Models.Team", b =>
                {
                    b.Navigation("MatchTeam1Navigations");

                    b.Navigation("MatchTeam2Navigations");
                });
#pragma warning restore 612, 618
        }
    }
}
